




.build_ano/uno/src/base.ino.cpp : src/base.ino
	@mkdir -p .build_ano/uno/src
	@echo [93msrc/base.ino[0m
	@/usr/bin/ano preproc --source-dir src  -o $@ $^


all : .build_ano/uno/src/base.ino.cpp
	@true

